### ISSUE TITLE
Manifest needs updating

### ISSUE THREAD

**Issue by emckee2006** [KoboldDM/free-kingmaker-remakes#1]
The latest manifest is still pointing at 2.1 instead of 2.5. Also, 2.5 isn't available in the foundry library?

**Comment by KoboldDM** [comment]
Thank you yes I'm aware, fix will be coming this weekend.

**Comment by emckee2006** [comment]
would a pull request help fix it sooner?

**Comment by KoboldDM** [comment]
Ah i see yeah, I can see about pushing this in an hour or two!

**Comment by emckee2006** [comment]
will you have to make a 2.6 with those changes?

**Comment by KoboldDM** [comment]
Nah I just made it 2.5 again. It works now

**Comment by emckee2006** [comment]
Thanks :)

Any estimate on when we get the next set of maps? Is there a tutorial or
something somewhere that shows the best way to use them? We are almost to
the hexploration portion of our game...

**Comment by KoboldDM** [comment]
Coming out now! And if you'd like help using them join the community Discord!
